### ISSUE TITLE
Installation document - Page not found

### ISSUE THREAD

**Issue by spmamidi** [codeforap/CFADeviceManager-Server#5]
Installation document link is not working, getting 404 error. Update the latest document url.

**Comment by satishvmadala** [comment]
Hi,
Siva, Please go through static data-vis folder's Readme file at https://github.com/codeforap/CFADeviceManager-Server/blob/master/data-vis/dashboard-static.md

Before we upload a stable server-version with dummy data, which can directly be downloaded and installed.

Meanwhile, will add you to the relevant discussions of this project. Please contribute internally.

**Comment by spmamidi** [comment]
Sure Satish. 

Moreover i would recommend CI server's and also will have gated checkin if possible, have you configured any CI Server. Each checkin will know unit tests status.
